import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navigation from '@/components/nav/Navigation'
import Header from '@/components/header/Header'
import Events from '@/components/events/Events'
import Footer from '@/components/footer/Footer'
import { client } from '@/client-api'
import { GetServerSideProps } from 'next'



export const getServerSideProps : GetServerSideProps = async () => {
  
  try {
    const response = await client.getEntries({
      content_type: 'event' 
    })
    return {
      props: {
        events: response.items
      }
    }
  } catch (error) {
    console.error('Error fetching events:', error)
    return {
      props: {
        events: []
      }
    }  
  }
}

type HomeProps = {
  events: any
}


export default function Home(
  {events} : HomeProps
  ) {
    const sortedEventsByDate = events.sort((a : any, b : any) => {
      return new Date(a.fields.startDateAndTime as string).getTime() - new Date(b.fields.startDateAndTime as string).getTime()
    })
    const upcomingEvent = sortedEventsByDate[0]
    const restOfEvents = sortedEventsByDate.slice(1)
  return (
    <>
      <Head>
        <title>Evenimente Inginerești - Descoperă evenimente inginerești din Romania</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navigation/>
        <Header upcomingEvent = {upcomingEvent}/>
        <Events events={restOfEvents}/>
        <Footer/>
      </main>
    </>
  )
}
